name: Test

on:
  push:
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache dependencies
        id: cache_dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        shell: bash
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build pretext
        shell: bash
        run: |
          cd node_modules/@chenglou/pretext
          wget https://raw.githubusercontent.com/chenglou/pretext/a52268864195edc76d5f382d264dafb33f6be462/tsconfig.build.json
          wget https://raw.githubusercontent.com/chenglou/pretext/a52268864195edc76d5f382d264dafb33f6be462/tsconfig.json
          ls -la
          npx --package typescript@6.0.2 tsc --version
          npx --package typescript@6.0.2 tsc -p tsconfig.build.json

      - name: Build prerequisites
        run: npx nx run-many -t build

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Test
        run: npx nx run-many -t test
